
name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install
        run: |
          npm install
      - name: TestCoverage
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@V1.3.1
        with:
          fullCoverageDiff: false
          runCommand: 'npx jest --collectCoverageFrom=''["**/*.{ts,tsx}"]'' --coverage --collectCoverage=true --coverageDirectory=''./'' --coverageReporters=''json-summary'' --ci'